#!/usr/bin/ruby

replaces = {
  "</head>"=>"head",
  "<body>"=>"body-top",
  "</body>"=>"body-bottom"
}
for k, v in replaces
  File.open("layout/#{v}.html", "rb") do |f| 
    replaces[k] = f.read.gsub(/\s*\n\s*/, '').to_s 
    replaces[k].gsub!(/(src|href)\=((\'|\")[^\'\"]+(\'|\"))/) do |m|
      n = m.split("=")
      n[1].gsub!(/[\'\"]/, '')
      unless n[1].match(/https:\/\//)
        n[1] = "https://www.ekylibre.org/spip#{'/' unless n[0].match(/^\//)}"+n[1]
      end
      n[1] = "\"#{n[1]}\""
      n.join("=")
    end
  end
end

for file in ARGV
  source = ""
  File.open(file, 'rb') { |f| source = f.read.to_s }
  for k, v in replaces
    source.gsub!(k, v)
  end
  File.open(file, 'wb') { |f| f.write(source) }
end
# for x in $*
# do
#     echo "Updating $x"
#     y=`cat layout/head.html`
#     sed -i -e "s/<\/head>/${y}<\/head>/g" ${x}

# done
